"""ai_analyst.py — Claude-powered monthly strategy analyst and code generator.

Each monthly review calls ``AIAnalyst.analyze()`` once. It receives the
month's trading results, the current EnsembleState, and a summary of the
grid-search step. It returns:

  - A qualitative narrative: what worked, what didn't, observed patterns.
  - Optionally, a new strategy proposal: a complete Python class that
    implements the Strategy Protocol (``name`` + ``on_bar``).

The proposal is then handed to ``strategy_sandbox.py`` for three layers of
validation before anything touches the ensemble. This module's only job is
calling the Anthropic API and parsing the response — all gate logic is
elsewhere.

Cost estimate
-------------
~$0.30–0.50 per monthly call using claude-opus-4-5. Runs exactly once per
month, so the annual AI cost for this feature is ~$4. The ANTHROPIC_API_KEY
must be set in ``.env``; the module raises ``RuntimeError`` otherwise so
the failure is obvious rather than silent.
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Model choice: Opus-class reasoning for code generation that runs autonomously
# on real capital. The cost premium (~$0.30/call) is trivial vs the downside of
# a buggy strategy generated by a cheaper model.
_MODEL = "claude-opus-4-5"

# Cross-system contract. The weekly analyst emits this marker on observations
# that have persisted ≥2 weeks; the monthly analyst scans for it as PRIMARY
# input to its proposals. Hardcoded as a constant here so a typo can't
# silently break the escalation pipeline. The .md prompts are read into the
# system prompt, so they reference the same literal — but only the analysts
# write it; Python code that READS for it must use this constant.
ESCALATION_MARKER = "WORTH ESCALATING TO MONTHLY REVIEW"

# Persistent-context files — the analyst's "brain". See ai-analyst/*.md docs.
# Project root: ai_analyst.py is at src/quant/agent/ai_analyst.py → 4 parents up.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
_ANALYST_DIR = _PROJECT_ROOT / "ai-analyst"
_ANALYST_MD = _ANALYST_DIR / "ANALYST.md"
_STRATEGY_LIBRARY_MD = _ANALYST_DIR / "STRATEGY_LIBRARY.md"
_EDGE_TAXONOMY_MD = _ANALYST_DIR / "EDGE_TAXONOMY.md"
_ANTI_PATTERNS_MD = _ANALYST_DIR / "ANTI_PATTERNS.md"
_MEMORY_MD = _ANALYST_DIR / "MEMORY.md"
_WEEKLY_ANALYST_MD = _ANALYST_DIR / "WEEKLY_ANALYST.md"

# The system prompt is BUILT at call time by concatenating:
#   1. ANALYST.md         → constitution (identity, standards, methodology)
#   2. STRATEGY_LIBRARY.md → canonical catalog of CURRENT active strategies
#                           + the trail_pct knob and operator hard rules
#   3. EDGE_TAXONOMY.md   → map of POSSIBLE strategy categories with
#                           coverage map (what's filled, what's a real gap)
#   4. ANTI_PATTERNS.md   → failure modes to check against before proposing
#   5. MEMORY.md          → append-only log of past proposals and outcomes
#   6. _RESPONSE_SHAPE    → the strict JSON schema the analyst must return
#
# This puts the analyst's persistent "brain" in front of every monthly call.
# The five .md files give it identity (1), current state (2), the space of
# possibilities (3), known failure modes (4), and history (5);
# the response shape ensures the output is mechanically parseable.

_RESPONSE_SHAPE = """\
════════════════════════════════════
RESPONSE FORMAT — raw JSON ONLY, no markdown fences
════════════════════════════════════
Return a single JSON object with this exact shape:

{
  "analysis": "<3–5 paragraph quantitative analysis. See ANALYST.md §6 for required workflow.>",
  "proposed_strategy": {
    "name": "<snake_case_with_params e.g. rsi_reversal_14_30>",
    "class_name": "<PascalCase e.g. RsiReversal>",
    "reasoning": "<Must include all 6 sections from ANALYST.md §2: edge thesis, math spec, regime analysis table, correlation hypothesis, statistical properties, falsification criteria>",
    "code": "<complete self-contained Python class string — see ANALYST.md §3>"
  } | null,
  "proposed_state_changes": {
    "trail_pct": <float in (0, 0.05] | null>,
    "sma_fast": <int in [10, 100] | null>,
    "sma_slow": <int in [50, 300] | null>,
    "mr_lookback": <int in [2, 30] | null>,
    "mr_threshold_pct": <float in (0.001, 0.1) | null>,
    "reasoning": "<quantitative evidence per ANALYST.md §6.5 — cite specific symbols, give-back magnitudes, or whipsaw counts from the daily runs table. Vague intuition is NOT acceptable.>"
  } | null,
  "pipeline_findings": [
    {
      "severity": "critical" | "high" | "medium" | "low",
      "category": "drift" | "dead_code" | "missing_safeguard" | "industry_norm",
      "description": "<1-2 sentences: what's wrong, with the specific numbers>",
      "recommendation": "<1-2 sentences: what to do about it>"
    },
    ...
  ]
}

ALL of the following are acceptable structures:
  - Strategy proposal AND state change   (both fields populated)
  - Strategy proposal only               (proposed_state_changes: null)
  - State change only                    (proposed_strategy: null)
  - Analysis only                        (both null — per ANALYST.md §7)
  - pipeline_findings: ALWAYS present (empty list if nothing found)

Use `proposed_strategy` for proposing a NEW strategy class.
Use `proposed_state_changes` for tuning the trailing-stop distance.
Use `pipeline_findings` for INFRASTRUCTURE issues you spotted in the
  monthly self-audit (config drift, dead code, missing safeguards,
  thresholds below institutional norms). See ANALYST.md §6 step 5c.
Use `analysis` text for everything else (qualitative commentary,
  regime observations, ensemble-mix opinions, etc.).
"""


def _read_file(path: Path) -> str:
    """Read a context file. Returns a placeholder if missing — never raises."""
    try:
        return path.read_text()
    except FileNotFoundError:
        logger.warning("ai_analyst: context file missing — %s", path)
        return f"(File {path.name} not found — operator should create it.)"


def _build_system_prompt() -> str:
    """Concatenate the five persistent .md files + response shape."""
    analyst_md = _read_file(_ANALYST_MD)
    library_md = _read_file(_STRATEGY_LIBRARY_MD)
    edge_md = _read_file(_EDGE_TAXONOMY_MD)
    anti_md = _read_file(_ANTI_PATTERNS_MD)
    memory_md = _read_file(_MEMORY_MD)
    return (
        f"# === ANALYST.md (your constitution) ===\n\n{analyst_md}\n\n"
        f"# === STRATEGY_LIBRARY.md (active strategies + tunable knobs) ===\n\n"
        f"{library_md}\n\n"
        f"# === EDGE_TAXONOMY.md (the space of possible edges + coverage map) ===\n\n"
        f"{edge_md}\n\n"
        f"# === ANTI_PATTERNS.md (failure modes — check against before proposing) ===\n\n"
        f"{anti_md}\n\n"
        f"# === MEMORY.md (your own past proposals + outcomes) ===\n\n{memory_md}\n\n"
        f"# === RESPONSE PROTOCOL ===\n\n{_RESPONSE_SHAPE}"
    )


def _build_weekly_system_prompt() -> str:
    """Build the WEEKLY analyst's system prompt — narrower than monthly.

    Weekly mode does NOT propose strategies or state changes; it writes a
    performance deep-dive. The prompt loads only the files the weekly
    analyst actually needs (saving ~7k tokens / ~$0.10/week vs reusing
    the monthly system prompt verbatim).
    """
    weekly_md = _read_file(_WEEKLY_ANALYST_MD)
    library_md = _read_file(_STRATEGY_LIBRARY_MD)
    memory_md = _read_file(_MEMORY_MD)
    return (
        f"# === WEEKLY_ANALYST.md (your role for this call) ===\n\n{weekly_md}\n\n"
        f"# === STRATEGY_LIBRARY.md (the ensemble you are analyzing) ===\n\n"
        f"{library_md}\n\n"
        f"# === MEMORY.md (history from the monthly analyst — context only) ===\n\n"
        f"{memory_md}\n\n"
        "# === RESPONSE PROTOCOL ===\n\n"
        "Return raw markdown ONLY — no JSON, no fences. The markdown will be "
        "embedded directly into the weekly review email. Follow the paragraph "
        "structure prescribed in WEEKLY_ANALYST.md §2. No preamble. No "
        "sign-off. Begin with the headline paragraph and end with the watch "
        "items.\n"
    )


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class StrategyProposal:
    """A proposed new strategy from the AI analyst."""
    name: str         # snake_case identifier used as the file name on disk
    class_name: str   # PascalCase — the class name inside the code
    reasoning: str    # human-readable explanation of the edge
    code: str         # complete Python source for the strategy class


@dataclass
class StateChangeProposal:
    """A proposed adjustment to a tunable EnsembleState field.

    Currently the only knob the analyst controls is ``trail_pct`` (the
    trailing-stop distance, see ANALYST.md §6.5). Future tunables can
    be added as optional fields — old months' MEMORY.md entries will
    simply have them absent.
    """
    trail_pct: float | None = None   # new trailing-stop distance, in (0, 0.05]
    # T4.22 — SMA + MR knobs are now tunable via the analyst's structured
    # channel. Each proposal MAY include any subset of these; None means
    # "no change to that knob". The operator-side apply path validates
    # the values before writing to EnsembleState.
    sma_fast: int | None = None      # new SMA fast window (typical 20-100)
    sma_slow: int | None = None      # new SMA slow window (typical 100-250)
    mr_lookback: int | None = None   # new MR MA window (typical 3-10)
    mr_threshold_pct: float | None = None    # new MR deviation threshold (0.005-0.05)
    reasoning: str = ""              # quantitative evidence for the change


@dataclass
class PipelineFinding:
    """A pipeline-quality issue the analyst spotted in the monthly self-audit.

    These are NOT strategy ideas. They are infrastructure/risk-config
    findings — drift between hardcoded constants and config values, dead
    risk-management features, missing institutional safeguards, etc.

    The monthly review surfaces them in a dedicated section of the email
    with the severity tag prominent. The operator decides whether/how to
    apply each fix. No auto-apply for these — pipeline changes touch
    safety-critical code and need human review.
    """
    severity: str             # "critical" | "high" | "medium" | "low"
    category: str             # "drift" | "dead_code" | "missing_safeguard" | "industry_norm"
    description: str          # 1-2 sentences: what's wrong
    recommendation: str       # 1-2 sentences: what to do about it


@dataclass
class AnalysisReport:
    """Full output of one AI analyst call."""
    analysis: str                         # qualitative narrative
    proposed_strategy: StrategyProposal | None  # None if no proposal
    proposed_state_changes: StateChangeProposal | None = None  # None if no tuning
    # Infrastructure/risk-config findings from the pipeline self-audit
    # (ANALYST.md §6 step 5c). Empty list when the analyst flagged nothing.
    pipeline_findings: list[PipelineFinding] = field(default_factory=list)


@dataclass
class WeeklyAnalysisReport:
    """Output of one weekly performance-review call.

    The weekly analyst does NOT propose strategies or state changes; its
    only deliverable is a structured deep-dive narrative the operator
    reads Saturday morning. See WEEKLY_ANALYST.md for the structure.
    """
    narrative: str   # markdown body, ~4-6 paragraphs per WEEKLY_ANALYST.md §2


# ---------------------------------------------------------------------------
# Prompt building helpers
# ---------------------------------------------------------------------------


def _summarise_runs(daily_runs: list[dict[str, Any]]) -> str:
    """Condense daily run records into a compact table for the prompt.

    Adds a Daily-Return column (equity[t] vs equity[t-1]) so the analyst
    can spot streaks, regime shifts, and bad/good days at a glance
    without having to compute the deltas in its head.
    """
    if not daily_runs:
        return "No daily runs available for the review period."

    sorted_runs = sorted(daily_runs, key=lambda r: r.get("date", ""))
    lines = [
        "Date       | Equity ($)  | Daily Δ% | Entries | Stops | Top-3 positions",
        "-----------|-------------|----------|---------|-------|----------------",
    ]
    prev_equity: float | None = None
    for run in sorted_runs:
        d = run.get("date", "?")
        er = run.get("execution_report", {})
        equity = er.get("account_equity_before")
        orders = er.get("submitted_orders", [])
        entries = sum(1 for o in orders if o.get("role") == "entry")
        stops = sum(1 for o in orders if o.get("role") == "stop_loss")
        targets: dict[str, float] = run.get("target_weights", {})
        top_names = ", ".join(
            sorted(targets, key=lambda s: -targets[s])[:3]
        ) if targets else "—"
        equity_str = f"{equity:>12,.0f}" if isinstance(equity, (int, float)) else f"{'?':>12}"
        # Daily return column — first row shows "—"; subsequent rows show
        # signed pct vs prior equity. This is a holding-only proxy since
        # equity is BEFORE today's trade, capturing yesterday's P&L.
        if isinstance(equity, (int, float)) and prev_equity and prev_equity > 0:
            ret_pct = (equity / prev_equity - 1.0) * 100
            ret_str = f"{ret_pct:+7.2f}%"
        else:
            ret_str = "      —"
        if isinstance(equity, (int, float)):
            prev_equity = float(equity)
        lines.append(
            f"{d} | {equity_str} | {ret_str} | {entries:>7} | {stops:>5} | {top_names}"
        )

    return "\n".join(lines)


def _render_past_weeklies(
    reports: list[dict[str, Any]],
    *,
    heading: str,
    empty_text: str,
) -> str:
    """Render up to N weekly narratives as a single markdown section.

    Shared between the monthly analyst's user message (where the heading
    frames them as "the weekly analyst's curated observations") and the
    weekly analyst's user message (where the heading frames them as the
    analyst's own past narratives for self-improvement). Same format,
    different framing supplied by the caller.
    """
    if not reports:
        return f"## {heading}\n\n_{empty_text}_\n\n"
    parts = [f"## {heading}", ""]
    for r in reports:
        parts.append(
            f"### Week ending {r.get('week_ending', '?')}\n\n"
            f"{r.get('narrative', '(no narrative recorded)')}"
        )
    return "\n\n".join(parts) + "\n\n"


def _build_user_message(
    daily_runs: list[dict[str, Any]],
    current_state: dict[str, Any],
    grid_search_summary: str,
    ai_strategy_names: list[str],
    recent_weekly_reports: list[dict[str, Any]] | None = None,
    monthly_metrics: dict[str, Any] | None = None,
    pipeline_snapshot: dict[str, Any] | None = None,
    quant_diagnostics: dict[str, Any] | None = None,
) -> str:
    """Compose the full user-turn message for the analyst call."""
    runs_table = _summarise_runs(daily_runs)
    state_json = json.dumps(current_state, indent=2)
    active_ai = (
        ", ".join(ai_strategy_names) if ai_strategy_names else "none yet"
    )

    # Recent weekly narratives — oldest first — give the monthly analyst
    # the weekly analyst's curated observations. Per ANALYST.md §6 step
    # 5a, the monthly analyst BUILDS ON these rather than re-deriving
    # attribution from raw daily data. Watch for "WORTH ESCALATING TO
    # MONTHLY REVIEW" markers from the weekly side.
    weekly_section = _render_past_weeklies(
        recent_weekly_reports or [],
        heading=(
            "Recent weekly reports — written by the WEEKLY analyst "
            "(your narrower self), oldest first"
        ),
        empty_text=(
            "No weekly reports available yet (fresh install or first month). "
            "Reason from raw daily data this time; future months will have "
            "weekly observations to build on."
        ),
    )

    # Monthly statistical view — pre-computed metrics over the full
    # 30-day window that the weekly summaries don't surface (lag-1
    # autocorrelation, day-of-week effects, position persistence, HRP
    # weight drift, streak runs, top-10 movers, raw daily-return series).
    # The analyst is directed (ANALYST.md §6 step 5b) to TRIANGULATE
    # these statistical patterns against the weekly narratives and the
    # raw daily-runs table.
    if monthly_metrics:
        metrics_section = (
            "## Monthly Statistical View — pre-computed over the full window "
            "(see ANALYST.md §6 step 5b: triangulate with weekly narratives + "
            "raw daily table)\n\n"
            f"```json\n{json.dumps(monthly_metrics, indent=2, default=str)}\n```\n\n"
        )
    else:
        metrics_section = ""

    # Pipeline snapshot — hardcoded constants + config values + wiring
    # status, bundled by monthly_review._build_pipeline_snapshot(). The
    # analyst must compare these against each other AND against the
    # industry norms (also in the snapshot) and emit findings under
    # `pipeline_findings`. See ANALYST.md §6 step 5c.
    if pipeline_snapshot:
        pipeline_section = (
            "## Pipeline Self-Audit — hardcoded knobs, config values, and "
            "wiring status (see ANALYST.md §6 step 5c)\n\n"
            "**You MUST review this block** and emit `pipeline_findings` "
            "for anything wrong. Specifically:\n"
            "  - Compare `operator_hard_rules_in_code` vs `config_yaml_values` "
            "    for the SAME risk knob. Any mismatch is a drift finding "
            "    (severity: high or critical).\n"
            "  - Check `wiring_status` for advertised-but-not-wired features. "
            "    A False there is dead code (severity: high).\n"
            "  - Compare `sandbox_gates_in_code` to "
            "    `industry_norms_for_comparison`. Anything looser than "
            "    institutional norms is a finding (severity: medium-high).\n"
            "  - If nothing is wrong, emit `pipeline_findings: []`. Don't "
            "    invent findings to look productive.\n\n"
            f"```json\n{json.dumps(pipeline_snapshot, indent=2, default=str)}\n```\n\n"
        )
    else:
        pipeline_section = ""

    # Quant diagnostics (Phase 4): the factor-attribution / signal-health /
    # regime bundle from monthly_diagnostics.build_quant_diagnostics. This
    # is the numbers substrate for the comprehensive review — it answers
    # "alpha or beta?", "which sleeve's edge has decayed?", and "what
    # regime are we in?" objectively. The analyst must reason across the
    # five pillars using THESE numbers, not vibes.
    if quant_diagnostics:
        diag_section = (
            "## Quant Diagnostics — alpha/beta, signal health, regime "
            "(Phase 4; reason across the 5 pillars using THESE numbers)\n\n"
            "Use this to drive the review:\n"
            "  - **Pillar 3 (alpha vs beta):** `attribution` gives the book's "
            "alpha (intercept) and factor `betas`. If alpha is ~0 and R² high, "
            "the book is just factor exposure — say so. Respect `n_obs`/"
            "`warnings`: a short-history alpha is directional only.\n"
            "  - **Pillar 1 (signal health):** `signal_health` has per-strategy "
            "IC, `decaying` flags, `turnover`, and `regime_ic`. A decayed or "
            "regime-dead sleeve is a candidate for retirement or regime-gating "
            "— escalate it.\n"
            "  - **Pillar 4 (risk/regime):** `regime.current`, the correlation "
            "de-gross signal, and `candidate_regime_policy` (sleeve multipliers "
            "for the current regime, derived from regime-conditional IC). "
            "Evaluate whether to adopt it via `proposed_state_changes.regime_"
            "policy` — it auto-applies behind backtest+shadow+DSR gates.\n"
            "  - **Pillars 2 & 5** stay your standard taxonomy-gap search and "
            "pipeline self-audit.\n\n"
            f"```json\n{json.dumps(quant_diagnostics, indent=2, default=str)}\n```\n\n"
        )
    else:
        diag_section = ""

    return (
        f"## Trading Results — last {len(daily_runs)} trading day(s) "
        "(daily-grain table; spot-check specific days here)\n\n"
        f"{runs_table}\n\n"
        f"{metrics_section}"
        f"## Current EnsembleState\n\n```json\n{state_json}\n```\n\n"
        f"## AI-Generated Strategies Already Active\n\n{active_ai}\n\n"
        f"## Monthly Grid-Search Results\n\n{grid_search_summary}\n\n"
        f"{weekly_section}"
        f"{diag_section}"
        f"{pipeline_section}"
        "---\nPlease analyze the results and propose a new strategy if appropriate. "
        "TRIANGULATE three sources before any proposal: (1) weekly narratives — "
        "curated attribution, (2) raw daily table — granular events, "
        "(3) monthly statistical view — longer-horizon patterns. "
        "If they DISAGREE (e.g., weekly attribution credits NVDA but the "
        "monthly day-of-week breakdown shows Monday underperformance is the "
        "real story), explicitly note the disagreement — that's a high-signal "
        f"finding. If weekly reports flagged anything '{ESCALATION_MARKER}', "
        "address those explicitly in your analysis and proposal decisions. "
        "FINALLY: complete the pipeline self-audit and emit `pipeline_findings` "
        "for any infrastructure issues you spotted."
    )


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------


class AIAnalyst:
    """Calls the Anthropic API to analyze trading results and generate strategies.

    Usage::

        analyst = AIAnalyst()
        report = analyst.analyze(
            daily_runs=runs,
            current_state={"sma_fast": 50, ...},
            ai_strategy_names=["rsi_reversal_14_30"],
            grid_search_summary="No change: no candidate beat current.",
        )
        print(report.analysis)
        if report.proposed_strategy:
            print(report.proposed_strategy.code)

    Raises ``RuntimeError`` if ``ANTHROPIC_API_KEY`` is not set.
    Raises ``ImportError`` if ``anthropic`` is not installed.
    """

    def __init__(self, model: str = _MODEL) -> None:
        # override=True ensures the .env value wins even if a blank
        # ANTHROPIC_API_KEY was already set in the shell environment.
        try:
            from dotenv import load_dotenv as _load  # noqa: PLC0415
            _load(override=True)
        except ImportError:
            pass
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            raise RuntimeError(
                "ANTHROPIC_API_KEY not set in .env. "
                "Get a key from console.anthropic.com and add:\n"
                "  ANTHROPIC_API_KEY=sk-ant-...\n"
                "to your .env file."
            )
        try:
            import anthropic  # noqa: PLC0415
        except ImportError as exc:
            raise ImportError(
                "anthropic package not installed. Run: uv sync"
            ) from exc
        self._client = anthropic.Anthropic(api_key=api_key)  # type: ignore[attr-defined]
        self._model = model

    def _create_message(self, **kwargs: Any):
        """``messages.create`` with retries tuned for the VPN deployment.

        The SDK's built-in retries cover 429/5xx but NOT 403 — and on
        this operator's network a 403 is almost never a real permission
        problem: it means the VPN exit IP landed on Anthropic's proxy/
        datacenter blocklist (see ``_describe_ai_failure``). Exit IPs
        rotate per connection, so a fresh attempt after a pause usually
        succeeds — the 2026-06-06 weekly review died on a single 403
        that a retry would likely have cleared. Long backoffs are fine:
        every caller is an unattended batch job.

        Connection errors (tunnel re-establishing, GFW interference)
        retry for the same reason. Genuine auth failures raise
        ``AuthenticationError`` (401), which is NOT retried.
        """
        import anthropic  # noqa: PLC0415

        from quant.util.retry import retry_on_transient  # noqa: PLC0415

        return retry_on_transient(
            lambda: self._client.messages.create(**kwargs),
            transient=(
                anthropic.PermissionDeniedError,   # 403 — blocklisted VPN exit IP
                anthropic.APIConnectionError,      # tunnel drop / GFW reset
            ),
            description="Anthropic messages.create",
            backoffs=(30.0, 60.0, 120.0),
        )

    def analyze(
        self,
        *,
        daily_runs: list[dict[str, Any]],
        current_state: dict[str, Any],
        ai_strategy_names: list[str] | None = None,
        grid_search_summary: str = "Grid search was not run this month.",
        recent_weekly_reports: list[dict[str, Any]] | None = None,
        monthly_metrics: dict[str, Any] | None = None,
        pipeline_snapshot: dict[str, Any] | None = None,
        quant_diagnostics: dict[str, Any] | None = None,
    ) -> AnalysisReport:
        """Call Claude to analyze results and optionally propose a new strategy.

        Parameters
        ----------
        daily_runs
            List of daily run payloads loaded via ``load_daily_run``.
        current_state
            ``EnsembleState`` serialized as a dict (via ``dataclasses.asdict``).
        ai_strategy_names
            Names of AI strategies already active in the ensemble (to avoid
            proposing duplicates).
        grid_search_summary
            Human-readable string from the monthly grid search step.
        recent_weekly_reports
            Past ~4 weekly narratives (oldest first) so the monthly analyst
            BUILDS ON the weekly analyst's curated observations instead of
            re-deriving attribution from raw daily data. Each is a dict
            with at least ``week_ending`` and ``narrative`` keys. Watch for
            ``ESCALATION_MARKER`` strings from the weekly side.

        Returns
        -------
        AnalysisReport
            Always contains ``analysis`` text. ``proposed_strategy`` is
            ``None`` when Claude decides no new strategy is needed.
        """
        user_msg = _build_user_message(
            daily_runs,
            current_state,
            grid_search_summary,
            ai_strategy_names or [],
            recent_weekly_reports=recent_weekly_reports,
            monthly_metrics=monthly_metrics,
            pipeline_snapshot=pipeline_snapshot,
            quant_diagnostics=quant_diagnostics,
        )
        logger.info(
            "ai_analyst: calling %s with %d daily runs", self._model, len(daily_runs)
        )

        # Rebuild the system prompt EACH call so MEMORY.md and STRATEGY_LIBRARY.md
        # updates from prior months are immediately visible.
        system_prompt = _build_system_prompt()
        message = self._create_message(
            model=self._model,
            max_tokens=8192,
            system=system_prompt,
            messages=[{"role": "user", "content": user_msg}],
        )
        raw = message.content[0].text.strip()
        logger.debug("ai_analyst raw response (first 500 chars): %s", raw[:500])

        data = _parse_json_response(raw)

        analysis_text = data.get("analysis", "(No analysis returned.)")
        proposal_data = data.get("proposed_strategy")

        proposal: StrategyProposal | None = None
        if proposal_data and isinstance(proposal_data, dict):
            try:
                proposal = StrategyProposal(
                    name=proposal_data["name"],
                    class_name=proposal_data["class_name"],
                    reasoning=proposal_data.get("reasoning", ""),
                    code=proposal_data["code"],
                )
            except KeyError as e:
                logger.warning(
                    "ai_analyst: proposed_strategy missing field %s — ignoring proposal", e
                )

        # Parse the optional state-change proposal (e.g., new trail_pct).
        # Validation here is light — type-coerce and clamp. The actual
        # gate (trail_pct ≤ STOP_LOSS_PCT) lives in monthly_review where
        # the proposal is surfaced to the operator.
        state_change_data = data.get("proposed_state_changes")
        state_change: StateChangeProposal | None = None
        if state_change_data and isinstance(state_change_data, dict):
            def _opt_float(key: str) -> float | None:
                raw = state_change_data.get(key)
                return float(raw) if raw is not None else None

            def _opt_int(key: str) -> int | None:
                raw = state_change_data.get(key)
                return int(raw) if raw is not None else None

            try:
                state_change = StateChangeProposal(
                    trail_pct=_opt_float("trail_pct"),
                    sma_fast=_opt_int("sma_fast"),
                    sma_slow=_opt_int("sma_slow"),
                    mr_lookback=_opt_int("mr_lookback"),
                    mr_threshold_pct=_opt_float("mr_threshold_pct"),
                    reasoning=str(state_change_data.get("reasoning", "")),
                )
            except (TypeError, ValueError) as e:
                logger.warning(
                    "ai_analyst: proposed_state_changes parse error: %s — ignoring",
                    e,
                )

        # Parse pipeline self-audit findings — list of {severity, category,
        # description, recommendation}. Empty list is the common "all clear"
        # case. Malformed entries are dropped with a warning.
        findings_raw = data.get("pipeline_findings") or []
        findings: list[PipelineFinding] = []
        if isinstance(findings_raw, list):
            for entry in findings_raw:
                if not isinstance(entry, dict):
                    continue
                try:
                    findings.append(PipelineFinding(
                        severity=str(entry.get("severity", "low")),
                        category=str(entry.get("category", "other")),
                        description=str(entry.get("description", "")),
                        recommendation=str(entry.get("recommendation", "")),
                    ))
                except (TypeError, ValueError) as e:
                    logger.warning(
                        "ai_analyst: pipeline_findings entry parse error: %s — skipping",
                        e,
                    )

        return AnalysisReport(
            analysis=analysis_text,
            proposed_strategy=proposal,
            proposed_state_changes=state_change,
            pipeline_findings=findings,
        )

    def analyze_weekly(
        self,
        *,
        daily_runs: list[dict[str, Any]],
        weekly_metrics: dict[str, Any],
        hrp_diagnostic: dict[str, Any] | None = None,
        past_weekly_reports: list[dict[str, Any]] | None = None,
    ) -> WeeklyAnalysisReport:
        """Call Claude to write a deep-dive analysis of the past week.

        Returns a markdown narrative the weekly review email embeds verbatim.
        Does NOT propose strategies or state changes — that's the monthly
        analyst's job (see WEEKLY_ANALYST.md §3).

        Parameters
        ----------
        daily_runs
            Daily run payloads from the past week (load_daily_run).
        weekly_metrics
            Pre-computed performance metrics for the week — return, Sharpe,
            max DD, win rate, attribution, concentration. See
            weekly_review._compute_weekly_metrics for the canonical builder.
        hrp_diagnostic
            Output of refit_hrp_weights' diag dict (per-strategy backtest
            stats, weight before/after). Helps the analyst reason about
            which strategies are gaining or losing weight and why.
        """
        runs_table = _summarise_runs(daily_runs)
        metrics_json = json.dumps(weekly_metrics, indent=2, default=str)
        hrp_json = json.dumps(hrp_diagnostic or {}, indent=2, default=str)

        # Past weekly reports — oldest first — for self-improvement per
        # WEEKLY_ANALYST.md §5. Same renderer the monthly call uses; only
        # the framing copy differs.
        past_section = _render_past_weeklies(
            past_weekly_reports or [],
            heading=(
                "Recent weekly reports — your own past narratives "
                "(oldest first) — see WEEKLY_ANALYST.md §5"
            ),
            empty_text=(
                "No past weekly reports yet — this is one of your first calls. "
                "Establish the baseline; future weeks will reference back to "
                "what you observe here."
            ),
        )

        user_msg = (
            f"## Past week's daily runs\n\n{runs_table}\n\n"
            f"## Pre-computed weekly metrics\n\n```json\n{metrics_json}\n```\n\n"
            f"## HRP refit diagnostic (this Saturday's refit)\n\n```json\n{hrp_json}\n```\n\n"
            f"{past_section}"
            "---\n\nWrite the weekly performance deep-dive per "
            "WEEKLY_ANALYST.md §2. Markdown only, no JSON, no fences. "
            "Begin with the headline paragraph; end with the watch items. "
            "If past reports exist, apply WEEKLY_ANALYST.md §5 — note "
            "continuity, self-critique, escalations."
        )
        logger.info(
            "ai_analyst: weekly call with %d daily runs", len(daily_runs)
        )

        system_prompt = _build_weekly_system_prompt()
        message = self._create_message(
            model=self._model,
            max_tokens=4096,
            system=system_prompt,
            messages=[{"role": "user", "content": user_msg}],
        )
        narrative = message.content[0].text.strip()
        # Strip accidental code fences if the model wrapped the output.
        if narrative.startswith("```"):
            lines = narrative.splitlines()
            # Drop opening fence + optional language tag.
            if lines and lines[0].startswith("```"):
                lines = lines[1:]
            # Drop closing fence.
            if lines and lines[-1].startswith("```"):
                lines = lines[:-1]
            narrative = "\n".join(lines).strip()

        return WeeklyAnalysisReport(narrative=narrative)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Persistence: append-only writes to MEMORY.md and STRATEGY_LIBRARY.md
# ---------------------------------------------------------------------------


def append_memory_entry(
    *,
    review_date: date,
    analysis: str,
    proposal: StrategyProposal | None,
    outcome: str,
    sandbox_details: str = "",
    grid_search_summary: str = "",
) -> None:
    """Append one monthly entry to MEMORY.md.

    Called by monthly_review.py AFTER the sandbox decision is known so the
    entry captures both what the analyst proposed AND what actually happened.

    Parameters
    ----------
    review_date    : ISO date of the monthly review
    analysis       : the analyst's qualitative narrative for this month
    proposal       : the StrategyProposal (or None if no proposal)
    outcome        : one of "accepted", "rejected", "no_proposal", "error"
    sandbox_details: sandbox metrics + rejection reason (if any)
    grid_search_summary: brief summary of the math grid search step
    """
    _ANALYST_DIR.mkdir(parents=True, exist_ok=True)

    proposal_block = (
        f"- **name**: `{proposal.name}`\n"
        f"- **class**: `{proposal.class_name}`\n"
        f"- **reasoning**:\n\n{proposal.reasoning}\n"
    ) if proposal else "_No strategy proposed this month._"

    entry = (
        f"\n### {review_date.isoformat()} — Monthly Review\n\n"
        f"**Grid-search step**: {grid_search_summary or '(none)'}\n\n"
        f"**Outcome**: `{outcome}`\n\n"
        f"**Sandbox result**: {sandbox_details or '(N/A)'}\n\n"
        f"**Analysis**:\n\n{analysis}\n\n"
        f"**Proposal**:\n\n{proposal_block}\n\n"
        f"---\n"
    )

    # Insert just above the insertion marker so newest stays near the bottom
    # (the marker comment is at the file's end, before "_End of MEMORY.md_").
    current = _MEMORY_MD.read_text() if _MEMORY_MD.exists() else (
        "# MEMORY.md\n\n<!-- ENTRIES_INSERTION_POINT -->\n\n_End of MEMORY.md_\n"
    )
    marker = "<!-- ENTRIES_INSERTION_POINT"
    if marker in current:
        before, after = current.split(marker, 1)
        # 'after' starts with the rest of the marker line; preserve it
        marker_line_end = after.find("\n")
        marker_line = marker + after[: marker_line_end + 1]
        rest = after[marker_line_end + 1 :]
        new_content = before + entry + marker_line + rest
    else:
        # Fallback: append at end
        new_content = current.rstrip() + "\n" + entry
    _MEMORY_MD.write_text(new_content)
    logger.info("ai_analyst: appended %s entry to MEMORY.md", review_date.isoformat())


def append_accepted_strategy_to_library(
    *,
    review_date: date,
    proposal: StrategyProposal,
    sharpe: float,
    max_drawdown: float,
    dsr: float,
) -> None:
    """Append an accepted AI strategy's full spec to STRATEGY_LIBRARY.md."""
    _ANALYST_DIR.mkdir(parents=True, exist_ok=True)

    entry = (
        f"\n### `{proposal.name}` — accepted {review_date.isoformat()}\n\n"
        f"**Class**: `{proposal.class_name}`\n\n"
        f"**Sandbox metrics at acceptance**:\n"
        f"- Sharpe: {sharpe:.3f}\n"
        f"- Max drawdown: {max_drawdown:.1%}\n"
        f"- DSR: {dsr:.3f}\n\n"
        f"**Reasoning at acceptance**:\n\n{proposal.reasoning}\n\n"
        f"**Code at acceptance**:\n\n"
        f"```python\n{proposal.code}\n```\n\n"
        f"---\n"
    )

    current = _STRATEGY_LIBRARY_MD.read_text() if _STRATEGY_LIBRARY_MD.exists() else (
        "# STRATEGY_LIBRARY.md\n\n<!-- AI_STRATEGIES_INSERTION_POINT -->\n"
    )
    marker = "<!-- AI_STRATEGIES_INSERTION_POINT -->"
    if marker in current:
        # Insert just after the marker so accepted strategies stack newest-at-top
        # within the Accepted AI Strategies section.
        new_content = current.replace(marker, marker + entry, 1)
    else:
        new_content = current.rstrip() + "\n" + entry
    _STRATEGY_LIBRARY_MD.write_text(new_content)
    logger.info(
        "ai_analyst: appended accepted strategy %s to STRATEGY_LIBRARY.md",
        proposal.name,
    )


# ---------------------------------------------------------------------------


def format_ai_error(exc: Exception) -> str:
    """Operator-friendly multi-line message for a failed analyst call.

    Why this exists: when the analyst dies, the review's email body used
    to be the raw ``f"{type(e).__name__}: {e}"``, e.g.
    ``PermissionDeniedError: Error code: 403 - {'error': {'type': 'forbidden',
    'message': 'Request not allowed'}}``. That tells the operator nothing
    about what to DO. This helper classifies the failure into one of three
    recoverable patterns and emits a recipe — including the exact CLI
    command to re-run the analyst (alone, no HRP refit) once the operator
    fixes the underlying issue.

    Patterns recognised:
      • HTTP 403 from Anthropic → almost always the VPN exit IP landed on
        Anthropic's edge deny-list. Recipe: switch VPN region and re-run
        with ``--ai-only``.
      • APIConnectionError / TLS reset / connection-pool error → upstream
        connection died mid-handshake. Almost always a network blip
        (VPN tunnel re-establishing, GFW interference). Recipe: re-run
        in a few minutes with ``--ai-only``.
      • Anything else → unclassified; show the raw exception but still
        include the ``--ai-only`` recipe so the operator has a recovery
        path.

    Returns a markdown-ready string suitable for dropping into the email.
    """
    exc_name = type(exc).__name__
    raw_msg = str(exc)

    # Anthropic returns a PermissionDeniedError on 403. We avoid importing
    # the anthropic module here (keeps this function callable from contexts
    # where anthropic isn't installed) and instead match by name + content.
    is_403 = (
        exc_name == "PermissionDeniedError"
        or "403" in raw_msg
        or "forbidden" in raw_msg.lower()
        or "request not allowed" in raw_msg.lower()
    )
    is_connection = (
        exc_name in {"APIConnectionError", "APITimeoutError", "ConnectionError"}
        or "connection" in raw_msg.lower() and "reset" in raw_msg.lower()
        or "connection error" in raw_msg.lower()
    )

    rerun_recipe = (
        "Once fixed, recover with:\n"
        "    uv run quant-weekly-review --for-date=YYYY-MM-DD --ai-only\n"
        "(or `quant-monthly-review --ai-only` for the monthly pipeline). "
        "The `--ai-only` flag skips the HRP refit / grid search and only "
        "re-fires the analyst, so the rest of the pipeline state stays "
        "untouched."
    )

    if is_403:
        return (
            f"_AI deep-dive failed: **Anthropic returned HTTP 403 "
            f"(`{exc_name}: {raw_msg[:200]}`)**._\n\n"
            "This is almost always Anthropic's CDN flagging the current "
            "VPN exit IP as a known proxy/datacenter address — NOT a code "
            "bug, NOT the API key. Most VPN providers rotate exit IPs "
            "continuously; one of today's IPs is on Anthropic's list.\n\n"
            "**Recipe**: switch VPN region (or restart the tunnel to "
            "pick a fresh IP), confirm with\n\n"
            "    curl -sS -o /dev/null -w '%{http_code}\\n' "
            "https://api.anthropic.com/v1/messages \\\n"
            "      -H \"x-api-key: $ANTHROPIC_API_KEY\" "
            "-H \"anthropic-version: 2023-06-01\" \\\n"
            "      -H \"content-type: application/json\" \\\n"
            "      -d '{\"model\":\"claude-opus-4-5\",\"max_tokens\":5,"
            "\"messages\":[{\"role\":\"user\",\"content\":\"ping\"}]}'\n\n"
            "(expect `200`). Then:\n\n"
            + rerun_recipe + "\n\n"
            "_The numeric summary and HRP refit below are still valid._"
        )
    if is_connection:
        return (
            f"_AI deep-dive failed: **upstream connection error "
            f"(`{exc_name}: {raw_msg[:200]}`)**._\n\n"
            "The TCP/TLS handshake to api.anthropic.com died mid-flight — "
            "typically the VPN tunnel re-establishing or transient GFW "
            "interference. Not a code bug.\n\n"
            "**Recipe**: wait a minute, confirm the tunnel is healthy "
            "(`curl -sS https://api.anthropic.com/v1/messages -o /dev/null -w "
            "'%{http_code}\\n' -H \"x-api-key: $ANTHROPIC_API_KEY\" "
            "-H \"anthropic-version: 2023-06-01\" -H \"content-type: "
            "application/json\" -d '{\"model\":\"claude-opus-4-5\","
            "\"max_tokens\":5,\"messages\":[{\"role\":\"user\","
            "\"content\":\"ping\"}]}'`), then:\n\n"
            + rerun_recipe + "\n\n"
            "_The numeric summary and HRP refit below are still valid._"
        )
    return (
        f"_AI deep-dive failed: `{exc_name}: {raw_msg[:300]}`._\n\n"
        "Unrecognised failure — check the launchd .out log for the full "
        "traceback. Once you understand the root cause:\n\n"
        + rerun_recipe + "\n\n"
        "_The numeric summary and HRP refit below are still valid._"
    )


def _parse_json_response(raw: str) -> dict[str, Any]:
    """Parse Claude's response as JSON.

    Claude occasionally wraps output in markdown code fences even when
    instructed not to. This handles both the clean case and the fenced case.
    """
    # Fast path: direct JSON.
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass

    # Fallback: extract the first {...} block (handles ```json ... ``` wrapping).
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass

    raise ValueError(
        f"ai_analyst: could not parse JSON from response. "
        f"First 300 chars: {raw[:300]!r}"
    )
