"""reports.py — markdown report renderers for the agent's emails.

Three audiences, three reports:

- ``render_daily_report``  — sent every weekday after the close. Summarizes
  TODAY'S trading: positions held, entries, stops, equity change.
- ``render_weekly_report`` — sent every Friday after close. Aggregates the
  week's daily runs; surfaces winning/losing names, hit rate, cost drag.
- ``render_monthly_report`` — sent end of month. Same shape as weekly but
  longer window, plus a "recommendations" section if the auto-improver
  has candidates.

Markdown output. The email sender attaches an HTML version too — for now
we use the raw markdown both as text and (via plain pre-wrapping) as HTML.
Markdown-to-HTML conversion is a v2 nicety.
"""

from __future__ import annotations

from datetime import date
from typing import Any

from quant.execution.alpaca_executor import ExecutionReport


def render_daily_report(
    *,
    run_date: date,
    strategy_name: str,
    target_weights: dict[str, float],
    execution_report: ExecutionReport,
) -> tuple[str, str]:
    """Render today's report. Returns (subject, markdown_body).

    The subject is short (~70 chars max so it doesn't wrap in inbox lists).
    """
    # Count both NEW entries (status=submitted in OTO bracket) AND KEPT
    # entries (carryforward positions where only the stop was re-armed).
    # Both represent positions that are now ON THE BOOKS — the subject
    # line should reflect total active positions, not just new ones.
    n_entries = sum(
        1 for o in execution_report.submitted_orders
        if o.role == "entry"
        and o.status in ("submitted", "skipped_dry_run", "kept")
    )
    n_stops = sum(
        1 for o in execution_report.submitted_orders
        if o.role == "stop_loss" and o.status in ("submitted", "skipped_dry_run")
    )
    n_failed = sum(
        1 for o in execution_report.submitted_orders if o.status == "failed"
    )
    subject = (
        f"quant agent — {run_date.isoformat()} — "
        f"{n_entries} entries, {n_stops} stops"
        + (f", {n_failed} FAILED" if n_failed else "")
    )

    lines: list[str] = []
    lines.append(f"# Quant agent — daily report — {run_date.isoformat()}")
    lines.append("")
    lines.append(f"**Strategy:** `{strategy_name}`  ")
    lines.append(f"**Environment:** `{execution_report.env}`  ")
    lines.append(
        f"**Account equity (pre-trade):** ${execution_report.account_equity_before:,.2f}  "
    )
    lines.append(f"**Dry run:** {execution_report.dry_run}")
    lines.append("")

    # --- Target book ---
    lines.append("## Target weights")
    lines.append("")
    if target_weights:
        lines.append("| Symbol | Weight |")
        lines.append("|---|---|")
        for sym, w in sorted(target_weights.items(), key=lambda kv: -kv[1]):
            lines.append(f"| {sym} | {w:+.2%} |")
    else:
        lines.append("_No target positions today (strategy returned no longs)._")
    lines.append("")

    # --- Pre-trade positions ---
    lines.append("## Positions at start of session")
    lines.append("")
    if execution_report.positions_before:
        lines.append("| Symbol | Qty |")
        lines.append("|---|---|")
        for sym, qty in sorted(execution_report.positions_before.items()):
            lines.append(f"| {sym} | {qty:+,d} |")
    else:
        lines.append("_Account was flat._")
    lines.append("")

    # --- Submitted orders ---
    lines.append("## Orders submitted")
    lines.append("")
    if execution_report.submitted_orders:
        lines.append("| Role | Symbol | Side | Qty | Stop price | Status | Alpaca ID |")
        lines.append("|---|---|---|---|---|---|---|")
        for o in execution_report.submitted_orders:
            stop = f"${o.stop_price:.2f}" if o.stop_price is not None else "—"
            err = f" *(err: {o.error})*" if o.error else ""
            oid = o.alpaca_order_id or "—"
            lines.append(
                f"| {o.role} | {o.symbol} | {o.side} | {o.qty:,d} | "
                f"{stop} | {o.status}{err} | `{oid}` |"
            )
    else:
        lines.append("_No orders were submitted (no rebalance needed)._")
    lines.append("")

    # --- Failures need their own emphasis. Buried in a long table they
    #     can be missed; surface them at the top of the agent's attention. ---
    failures = [o for o in execution_report.submitted_orders if o.status == "failed"]
    if failures:
        lines.append("## ⚠ Failures")
        lines.append("")
        for o in failures:
            lines.append(f"- **{o.symbol}** {o.side} {o.qty}: {o.error}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by `quant.agent.daily_runner`._")

    return subject, "\n".join(lines) + "\n"


def render_weekly_report(
    *,
    week_ending: date,
    daily_runs: list[dict[str, Any]],
    equity_curve: dict[date, float] | None = None,
    notes: str = "",
) -> tuple[str, str]:
    """Render a weekly summary.

    ``daily_runs`` is a list of the per-day payloads loaded from
    ``log.load_daily_run``. ``equity_curve`` is optional; if provided
    we add a returns line.
    """
    subject = f"quant agent — weekly review — week ending {week_ending.isoformat()}"

    lines: list[str] = []
    lines.append(f"# Quant agent — weekly review — week ending {week_ending.isoformat()}")
    lines.append("")
    lines.append(f"**Runs included:** {len(daily_runs)} trading days  ")
    if equity_curve and len(equity_curve) >= 2:
        eq_dates = sorted(equity_curve.keys())
        start_eq = equity_curve[eq_dates[0]]
        end_eq = equity_curve[eq_dates[-1]]
        pnl = end_eq - start_eq
        ret_pct = (end_eq / start_eq - 1) if start_eq > 0 else 0.0
        lines.append(f"**Equity:** ${start_eq:,.2f} → ${end_eq:,.2f}  ")
        lines.append(f"**P&L this week:** ${pnl:+,.2f} ({ret_pct:+.2%})  ")
    lines.append("")

    # Aggregate stats from the daily runs. Count only NEW broker entries
    # ("submitted") — "kept" rows are carryforward and don't represent
    # new trading activity. This number is "how many new entries did
    # the system make this week", which is the operator-facing metric.
    n_entries = sum(
        1
        for run in daily_runs
        for o in run.get("execution_report", {}).get("submitted_orders", [])
        if o.get("role") == "entry" and o.get("status") == "submitted"
    )
    n_stops = sum(
        1
        for run in daily_runs
        for o in run.get("execution_report", {}).get("submitted_orders", [])
        if o.get("role") == "stop_loss" and o.get("status") == "submitted"
    )
    n_failed = sum(
        1
        for run in daily_runs
        for o in run.get("execution_report", {}).get("submitted_orders", [])
        if o.get("status") == "failed"
    )

    lines.append("## Activity")
    lines.append("")
    lines.append("| Item | Value |")
    lines.append("|---|---|")
    lines.append(f"| Entry orders | {n_entries} |")
    lines.append(f"| Stop-loss orders | {n_stops} |")
    lines.append(f"| Failed orders | {n_failed} |")
    lines.append("")

    # Per-day equity if available.
    if equity_curve:
        lines.append("## Daily equity")
        lines.append("")
        lines.append("| Date | Equity |")
        lines.append("|---|---|")
        for d in sorted(equity_curve.keys()):
            lines.append(f"| {d.isoformat()} | ${equity_curve[d]:,.2f} |")
        lines.append("")

    if notes:
        lines.append("## Notes")
        lines.append("")
        lines.append(notes)
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by `quant.agent.weekly_review`._")
    return subject, "\n".join(lines) + "\n"


def render_monthly_report(
    *,
    month_ending: date,
    daily_runs: list[dict[str, Any]],
    equity_curve: dict[date, float] | None = None,
    recommendations: list[str] | None = None,
) -> tuple[str, str]:
    """Render a monthly summary. Like the weekly but with a Recommendations
    section populated by the auto-improver."""
    subject = (
        f"quant agent — monthly review — "
        f"month ending {month_ending.isoformat()}"
    )

    # Reuse the weekly renderer for the core stats, then bolt on recs.
    _, body = render_weekly_report(
        week_ending=month_ending,
        daily_runs=daily_runs,
        equity_curve=equity_curve,
    )
    body = body.replace(
        "quant agent — weekly review",
        "quant agent — monthly review",
    ).replace(
        "_Generated by `quant.agent.weekly_review`._",
        "",
    )

    extra: list[str] = []
    if recommendations:
        extra.append("## Recommendations")
        extra.append("")
        for r in recommendations:
            extra.append(f"- {r}")
        extra.append("")
    extra.append("---")
    extra.append("")
    extra.append("_Generated by `quant.agent.monthly_review`._")

    return subject, body.rstrip() + "\n\n" + "\n".join(extra) + "\n"
